import Head from "next/head";
import { useEffect } from "react";
import Header from "../components/Header";
import "../styles/globals.css";
import { MoralisProvider } from "react-moralis";
import { NotificationProvider } from "web3uikit";
import Script from "next/script";

import { ApolloProvider, ApolloClient, InMemoryCache } from "@apollo/client";
import Footer from "../components/Footer";

const client = new ApolloClient({
  cache: new InMemoryCache(),
  uri: "https://api.studio.thegraph.com/query/32380/dynamic-month-nfts/v0.0.3",
});

function MyApp({ Component, pageProps }) {
  useEffect(() => {
    const use = async () => {
      (await import("tw-elements")).default;
    };
    use();
  }, []);

  return (
    <div className="bg-gradient-to-r from-[#0F2027] via-[#203A43] to-[#2C5364] max-w-full mx-auto min-h-screen text-white ">
      {/* // <div className="bg-gradient-to-r from-[#141E30]  to-[#243B55] max-w-full mx-auto min-h-screen text-white "> */}
      <MoralisProvider initializeOnMount={false}>
        <ApolloProvider client={client}>
          <NotificationProvider>
            <Script src="./TW-ELEMENTS-PATH/dist/js/index.min.js"></Script>
            <Head>
              <title>Dynamic Month NFT</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="max-w-[90%] mx-auto">
              <Header />
              <Component {...pageProps} />
            </div>
            {/* <Footer /> */}
          </NotificationProvider>
        </ApolloProvider>
      </MoralisProvider>
    </div>
  );
}

export default MyApp;
